/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CachedDate: typeof import('./src/components/study/cached-date.vue')['default']
    Message: typeof import('primevue/message')['default']
    QuestionWatcher: typeof import('./src/components/question-watcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskItem: typeof import('./src/components/task-item.vue')['default']
    TaskList: typeof import('./src/components/task-list.vue')['default']
  }
}

// For TSX support
declare global {
  const CachedDate: typeof import('./src/components/study/cached-date.vue')['default']
  const Message: typeof import('primevue/message')['default']
  const QuestionWatcher: typeof import('./src/components/question-watcher.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TaskItem: typeof import('./src/components/task-item.vue')['default']
  const TaskList: typeof import('./src/components/task-list.vue')['default']
}